name: Build

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      buildType:
        description: "Build Type"
        required: false
        default: "MinSizeRel"
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ inputs.buildType }}

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: Install conan
        run: sudo pip install "conan>2.0"

      - name: Install Unar
        run: sudo apt-get install -q unar

      - name: Get & Extract Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r26d-linux.zip -O android-ndk.zip
          sudo unzip -qq android-ndk.zip
          mv android-ndk-* android-ndk
          ls
          ls android-ndk
      
      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan2/p
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.py') }}
          restore-keys: ${{ runner.os }}-conan-

      - name: Cache CMake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build
          key: ${{ runner.os }}-cmake

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DGTPROXY_BUILD_VERSION=${{github.run_number}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_NDK=${{github.workspace}}/android-ndk -DANDROID_ABI="arm64-v8a" -DANDROID_NATIVE_API_LEVEL="android-21"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Move program and binary
        run: |
          mkdir ${{github.workspace}}/output
          cp ${{github.workspace}}/build/src/${{env.BUILD_TYPE}}/* ${{github.workspace}}/output
          ls ${{github.workspace}}/build/src/${{env.BUILD_TYPE}}/
          cp ${{github.workspace}}/build/conan/build/* ${{github.workspace}}/output
          ls ${{github.workspace}}/build/conan/build/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtproxy-${{github.sha}}
          path: ${{github.workspace}}/output
